# Generated by Django 6.0 on 2025-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modbus_id', models.PositiveIntegerField(unique=True)),
                ('min_position', models.IntegerField(default=0)),
                ('max_position', models.IntegerField(default=4095)),
                ('offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('loop_interval_ms', models.PositiveIntegerField(default=100)),
                ('kp', models.FloatField(default=1.0, help_text='Proportional Gain')),
                ('ki', models.FloatField(default=0.0, help_text='Integral Gain')),
                ('kd', models.FloatField(default=0.0, help_text='Derivative Gain')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Profilometer', max_length=50)),
                ('target_value', models.FloatField(default=0.0, help_text='Target profile reading value')),
                ('tolerance', models.FloatField(default=0.5, help_text='Acceptable deviation (+/-)')),
            ],
        ),
    ]
