# Generated by Django 4.2.27 on 2025-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileconfig',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='Use simulated value instead of partial sensor reading'),
        ),
        migrations.AddField(
            model_name='profileconfig',
            name='simulated_value',
            field=models.FloatField(default=10.0, help_text='Value to use when in simulation mode'),
        ),
    ]
